apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.poweruser_crb_name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.poweruser_cluster_role | quote }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.poweruser_client_role | quote }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.poweruser_client_role | quote }}
