# 'ec2-instance' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c ec2-instance' or 'atmos vendor pull --component ec2-instance'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/ec2-instance?ref={{ .Version }}
    version: 1.423.0
    included_paths:
      - "**/**"
    excluded_paths: []
