# example to fetch all secrets underneath the `/app/` prefix (service).
# Keys are rewritten within the K8S Secret to be predictable and omit the
# prefix.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: "secret-store-parameter-store" # Must match name of the Cluster Secret Store created by this component
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: app-secrets
  dataFrom:
  - find:
      name:
        regexp: "^/app/" # Match the path prefix of your service
    rewrite:
    - regexp:
        source: "/app/(.*)" # Remove the path prefix of your service from the name before creating the envars
        target: "$1"
