# example to fetch a single secret from our Parameter Store `SecretStore`

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: single-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: "secret-store-parameter-store" # Must match name of the Cluster Secret Store created by this component
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: single-secret
  data:
  - secretKey: good_secret
    remoteRef:
      key: /app/good_secret
