rbac:
  create: true
installCRDs: true
serviceAccount:
  create: true
prometheus:
  servicemonitor:
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
webhook:
  enabled: true
cainjector:
  enabled: true
