# https://pkg.go.dev/github.com/terraform-docs/terraform-docs/terraform#Module
content: |-
  {{- $context_variables := list "context" "enabled" "namespace" "tenant" "environment" "stage" "name" "delimiter" "attributes" "tags" "additional_tag_map" "label_order" "regex_replace_chars" "id_length_limit" "label_key_case" "label_value_case" "descriptor_formats" "labels_as_tags" -}}
  {{- define "variableDescription" -}}
  ### `{{ .Name }}`{{ if lt (len (split "\n" (tostring .Type))) 2 }} (`{{ tostring .Type }}`){{end}} <i>{{ ternary .Required "required" "optional" }}</i>{{ if contains "OBSOLETE: " (tostring .Description) }} <strong>OBSOLETE</strong>{{ end }}

  {{ $lines := regexSplit "\n" (tostring .Description | replace "OBSOLETE: " "") -1 -}}
  {{- range $lines }}
  {{ . }}<br/>
  {{- end }}

  >
  > <dl>
  >   <dt>Required</dt>
  >   <dd>{{ ternary .Required "Yes" "No" }}</dd>
  >   <dt>Type</dt>
  >   <dd>
  >   {{ if lt (len (split "\n" (tostring .Type))) 2 }}<code>{{ tostring .Type }}</code>{{ else }}
  >
  >   ```hcl
  >   {{ .Type.Raw }}
  >   ```
  >
  >   {{ end }}
  >   </dd>
  >
  >   <dt>Default value</dt>
  >   <dd>
  >   {{ if lt (len (split "\n" .GetValue)) 2 }}<code>{{ .GetValue | default "unset" }}</code>{{ else }}
  >
  >   ```hcl
      {{- $lines := regexSplit "\n" .GetValue -1 -}}
      {{- range $lines }}
  >   {{ . }}
      {{- end }}
  >   ```
  >
      {{- end }}
  >   </dd>
  > </dl>
  >

  {{ end -}}

  {{ .Header }}


  {{ if ne (len .Module.Requirements) 0 -}}
  ## Version Requirements

  | Requirement | Version |
  | --- | --- |
  {{- range .Module.Requirements }}
  | `{{ .Name }}` | {{ tostring .Version | default "latest" }} |
  {{- end }}
  {{ end }}

  {{ if ne (len .Module.Providers) 0 -}}
  ## Providers

  | Provider | Version |
  | --- | --- |
  {{- range .Module.Providers }}
  | `{{ .Name }}` | {{ tostring .Version | default "latest" }} |
  {{- end }}
  {{ end }}

  {{ if ne (len .Module.ModuleCalls) 0 -}}
  ## Modules

  Name | Version | Source | Description
  --- | --- | --- | ---
  {{ range .Module.ModuleCalls }}
  {{- $baseUrl := "https://registry.terraform.io/modules" -}}
  {{ if contains "//" .Source -}}
    {{- $moduleParts := regexSplit "//" .Source 2 -}}
    {{- $moduleName := first $moduleParts -}}
    {{- $submodulePath := last $moduleParts | replace "modules/" "" -}}
    {{- /* https://registry.terraform.io/modules/cloudposse/stack-config/yaml/latest/submodules/remote-state */ -}}
    `{{ .Name }}` | {{ .Version | default "latest" }} | {{ printf "[`%s`](%s/%s/%s/submodules/%s)" .Source $baseUrl $moduleName .Version $submodulePath }} | {{ tostring .Description | default "n/a" }}
  {{ else -}}
    `{{ .Name }}` | {{ .Version | default "latest" }} | {{ printf "[`%s`](%s/%s/%s)" .Source $baseUrl .Source .Version }} | {{ tostring .Description | default "n/a" }}
  {{ end }}
  {{- end -}}
  {{- end -}}

  {{- if ne (len .Module.Resources) 0 }}

  ## Resources

  The following resources are used by this module:
  {{ range .Module.Resources }}
    {{- $isResource := and $.Config.Sections.Resources ( eq "resource" (printf "%s" .GetMode)) }}
    {{- if $isResource }}
    {{- $fullspec := ternary .URL (printf "[`%s`](%s)" .Spec .URL) .Spec }}
    - {{ $fullspec }} {{ printf "(%s)" .GetMode -}} ({{ .Position.Filename }}#{{ .Position.Line }})
    {{- end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Resources) 0 -}}
  ## Data Sources

  The following data sources are used by this module:
  {{ range .Module.Resources }}
    {{- $isDataResource := and $.Config.Sections.DataSources ( eq "data source" (printf "%s" .GetMode)) }}
    {{- if $isDataResource }}
    {{- $fullspec := ternary .URL (printf "[`%s`](%s)" .Spec .URL) .Spec }}
    - {{ $fullspec }} {{ printf "(%s)" .GetMode -}}
    {{- end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Outputs) 0 -}}
  ## Outputs

  <dl>
  {{- range .Module.Outputs }}
    <dt><code>{{ .Name }}</code>{{ if contains "OBSOLETE: " (tostring .Description) }} <strong>OBSOLETE</strong>{{ end }}</dt>
    <dd>

    {{ $lines := regexSplit "\n" (tostring .Description | replace "OBSOLETE: " "" | default "n/a" ) -1 -}}
    {{- range $lines }}
    {{ . }}<br/>
    {{- end }}

    </dd>
  {{- end }}
  </dl>
  {{- end }}

  ## Required Variables

  Required variables are the minimum set of variables that must be set to use this module.

  > [!IMPORTANT]
  >
  > To customize the names and tags of the resources created by this module, see the [context variables](#context-variables).
  >

  {{- range .Module.Inputs }}
  {{- if and (not (has .Name $context_variables)) .Required }}
  {{ template "variableDescription" . }}
  {{- end }}
  {{- end }}

  {{ $optional := false -}}
  {{ range .Module.Inputs }}{{ if not .Required }}{{ $optional = true -}}{{ end -}}{{ end -}}

  {{ if $optional -}}
  ## Optional Variables

  {{- range .Module.Inputs }}
  {{- if and (not (has .Name $context_variables)) (not .Required) }}
  {{ template "variableDescription" . }}
  {{- end -}}
  {{ end -}}
  {{ end }}

  ## Context Variables

  The following variables are defined in the `context.tf` file of this module and part of the [terraform-null-label](https://registry.terraform.io/modules/cloudposse/label/null) pattern. These are identical in all Cloud Posse modules.

  <details>
  <summary>Click to expand</summary>

  {{ range .Module.Inputs }}
  {{- if and (has .Name $context_variables) }}
  {{ template "variableDescription" . }}
  {{- end }}
  {{- end }}

  </details>



formatter: "markdown document" # this is required
version: ""
#header-from: ".header.md"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

sort:
  enabled: true
  by: required

output-values:
  enabled: false
  from: ''

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true




