datadog:
  logLevel: INFO
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  collectEvents: true
  leaderElection: true
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  apm:
    enabled: false
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enableTCPQueueLength: true
    enableOOMKill: true
    collectDNSStats: true
    enableConntrack: true
    bpfDebug: false
  networkMonitoring:
    enabled: true
  clusterChecksRunner:
    enabled: false
  clusterChecks:
    enabled: true
  dogstatsd:
    useHostPort: true
    nonLocalTraffic: true
  securityAgent:
    runtime:
      enabled: true
    compliance:
      enabled: true
  helmCheck:
    enabled: true
    collectEvents: true
clusterAgent:
  enabled: true
  replicas: 1
  metricsProvider:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
agents:
  priorityClassName: "system-node-critical"
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
# Per https://github.com/DataDog/helm-charts/blob/main/charts/datadog/README.md#configuration-required-for-amazon-linux-2-based-nodes
  podSecurity:
    apparmor:
      enabled: false
