authSecret:
  create: false
  name: controller-manager
scope:
  # If true, the controller will only watch custom resources in a single namespace,
  # which by default is the namespace the controller is in.
  # This provides the ability to run multiple controllers in different namespaces
  # with different TOKENS to get around GitHub API rate limits, among other things.
  singleNamespace: true
syncPeriod: 120s

githubWebhookServer:
  enabled: false
  syncPeriod: 120s
  secret:
    # Webhook secret, used to authenticate incoming webhook events from GitHub
    # When using Sops, stored in same SopsSecret as authSecret under key `github_webhook_secret_token`
    enabled: true
    create: false
    name: "controller-manager"
  useRunnerGroupsVisibility: false
  ingress:
    enabled: false
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      # Use the default ingress, or uncomment and set the group name to use a different one
      # alb.ingress.kubernetes.io/group.name: common
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/target-type: ip
    podDisruptionBudget:
      maxUnavailable: "60%"
