apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "echo-server.fullname" . }}
  labels:
    {{- include "echo-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "echo-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "echo-server.fullname" . }}
      labels:
        {{- include "echo-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          # Disable the feature that turns the echo server into a file browser on the server (security risk)
          - "--enable:file=false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
