apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - _all.yaml

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=argocd,app.kubernetes.io/component=dex-server"