#!/bin/bash

function usage() {
  cat >&2 <<'EOF'
./karpenter-crd-upgrade

Use this script to prepare a cluster for karpenter-crd helm chart support by upgrading Karpenter CRDs.

EOF
}

function upgrade() {
  set -x

  kubectl label crd awsnodetemplates.karpenter.k8s.aws provisioners.karpenter.sh app.kubernetes.io/managed-by=Helm --overwrite
  kubectl annotate crd awsnodetemplates.karpenter.k8s.aws provisioners.karpenter.sh meta.helm.sh/release-name=karpenter-crd --overwrite
  kubectl annotate crd awsnodetemplates.karpenter.k8s.aws provisioners.karpenter.sh meta.helm.sh/release-namespace=karpenter --overwrite
}

if (($# == 0)); then
  upgrade
else
  usage
fi
