# 'lambda' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c lambda' or 'atmos vendor pull --component lambda'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/lambda?ref={{ .Version }}
    version: 1.122.0
    included_paths:
      - "**/**"
    excluded_paths: []
