## Initialize the configuration (should only be run once)
init:
	@scripts/$@.sh

## Destroy the configuration (only works if `force_destroy=true`)
destroy:
	@scripts/$@.sh

## Force destroy the bucket (not recommended!)
force-destroy:
	@scripts/$@.sh
