apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.release_name }}
spec:
  replicas: 1
  template:
    spec:
      # You could reserve nodes for runners by labeling and tainting nodes with
      #   node-role.kubernetes.io/actions-runner
      # and then adding the following to this RunnerDeployment
      #
      #  nodeSelector:
      #    node-role.kubernetes.io/actions-runner: ""
      #
      #  tolerations:
      #  - effect: NoSchedule
      #    key: node-role.kubernetes.io/actions-runner
      #    operator: Exists

      {{ if eq .Values.type "org" }}
      organization: {{ .Values.target }}
      {{ end }}
      {{ if eq .Values.type "repo" }}
      repository: {{ .Values.target }}
      {{ end }}
      # You can use labels to create subsets of runners.
      # See https://github.com/summerwind/actions-runner-controller#runner-labels
      # and https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow
      dockerdWithinRunnerContainer: true
      image: {{ .Values.runners_image | quote }}
      imagePullPolicy: IfNotPresent
      serviceAccountName: {{ .Values.service_account_name }}
      resources:
        {{- toYaml .Values.runner_resources.resources | nindent 8 }}
