## Initialize terraform remote state
init:
	init-terraform

## Show terraform plan for this project
plan:
	terraform plan

## Apply terraform plan for this project
apply:
	terraform apply

## Destroy terraform project
destroy:
	terraform destroy
