apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "secret-store-parameter-store"
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.region }}
      role: {{ .Values.role }} # role is created via helm-release; see `service_account_set_key_path`
