name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Install terraform to ensure we're using our expected version
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - uses: actions/checkout@v2

      # Install terraform-docs for pre-commit hook
      - name: Install terraform-docs
        shell: bash
        env:
          INSTALL_PATH: "${{ github.workspace }}/bin"
        run: |
          make init
          mkdir -p "${INSTALL_PATH}"
          make packages/install/terraform-docs
          echo "$INSTALL_PATH" >> $GITHUB_PATH

      # pre-commit setup
      - uses: actions/setup-python@v2
      # pre-commit checks: fmt + terraform-docs
      # We skip tf_validate as it requires an init
      # of all root modules, which is to be avoided.
      - uses: pre-commit/action@v2.0.2
        env:
          SKIP: tf_validate
        with:
          token: ${{ secrets.CODE_OWNER_VALIDATION }}
          extra_args: --all-files
